unmessy api{
    src{
        api{
            middleware{
                auth.js
                error-handler.js
                rate-limit.js
                request-logger.js
                validate-input.js
        }
        routes{
            admin.js
            health.js
            hubspot-webhook.js
            validate.js
        }
        Server.js
    }
    core{
        config.js
        db.js
        errors.js
        logger.js
    }
    monitoring{
        alert.js
        metrics.js
    }
    scripts{
        health-check.js
        migrate.js
        test-connect.js
    }
    services{
        external{
            hubspot.js
            opencage.js
            zerobounce.js
        }
        validation{
            name-validation-service.js
            email-validation-service.js
            phone-validation-service.js
            address-validation-service.js
        }
        client-service.js
        queue-service.js
        validation-service.js
        test{
            integration{
                api.test.js
                queue.test.js
            }
            load{
                stress-test.js
            }
            unit{

            }
        }
       
        workers{
            queue-monitor.js
            queue-processor.js
        }
        index.js
    }
    package-Lock.json
    package.json
    vercel.json
}